---
- name: Install common packages
  apt:
    name: ['nginx', 'php-fpm', 'php-mysql', 'mysql-server', 'mysql-client', 'php-curl', 'php-gd']
    state: present
  become: true

- name: Copy PHP-FPM config
  template:
    src: php-fpm.ini.j2
    dest: /etc/php/7.4/fpm/php.ini
  become: true

- name: Copy Nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  become: true

- name: Enable and start services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - php7.4-fpm
    - nginx
  become: true

